// Generated by scripts/generate-quicklook-config.js — do not edit manually.

import Foundation

/// Finder Quick Look union + layout config from config/quickLookUnion.js
enum GeneratedQuickLookConfig {
    /// Maximal Finder admission set (macOS routes by UTI → calls this extension).
    static let unionExtensions: Set<String> = [
        "3dm",
        "3ds",
        "3mf",
        "7z",
        "amf",
        "arrow",
        "avro",
        "bash",
        "basis",
        "brep",
        "brp",
        "bvh",
        "c",
        "cjs",
        "cpp",
        "cs",
        "css",
        "csv",
        "dae",
        "db",
        "dcm",
        "dicom",
        "doc",
        "dockerfile",
        "docx",
        "drc",
        "dwg",
        "dxf",
        "fbx",
        "feather",
        "fit",
        "fits",
        "fts",
        "gcode",
        "glb",
        "gltf",
        "go",
        "graphql",
        "gz",
        "h5",
        "hdf5",
        "ifc",
        "iges",
        "igs",
        "java",
        "js",
        "json",
        "jsonl",
        "jsx",
        "kicad_pcb",
        "kicad_pro",
        "kicad_sch",
        "kicad_wks",
        "kmz",
        "kt",
        "ktx2",
        "las",
        "laz",
        "less",
        "log",
        "lwo",
        "makefile",
        "mat",
        "md",
        "md2",
        "mdd",
        "mjs",
        "mmd",
        "mpd",
        "ndjson",
        "npy",
        "npz",
        "nrrd",
        "obj",
        "ods",
        "parquet",
        "pcd",
        "pdb",
        "php",
        "ply",
        "pmx",
        "ppt",
        "pptx",
        "py",
        "rar",
        "rb",
        "rs",
        "sass",
        "scss",
        "sh",
        "sql",
        "sqlite",
        "sqlite3",
        "step",
        "stl",
        "stp",
        "tar",
        "tilt",
        "toml",
        "ts",
        "tsv",
        "tsx",
        "ttf",
        "txt",
        "usdz",
        "vox",
        "vrml",
        "vtk",
        "vtp",
        "wrl",
        "xls",
        "xlsx",
        "xml",
        "xyz",
        "yaml",
        "yml",
        "zip",
        "zsh",
    ]

    static let previewMimeTypes: [String: String] = [
        "3dm": "application/x-3dm",
        "3ds": "application/x-3ds",
        "3mf": "application/vnd.ms-package.3dmanufacturing-3dmodel+xml",
        "7z": "application/x-7z-compressed",
        "amf": "application/x-amf",
        "arrow": "application/vnd.apache.arrow.file",
        "avro": "application/avro",
        "bash": "text/x-sh",
        "basis": "image/basis",
        "brep": "application/octet-stream",
        "brp": "application/octet-stream",
        "bvh": "application/octet-stream",
        "c": "text/x-c",
        "cjs": "text/javascript",
        "cpp": "text/x-c++src",
        "cs": "text/x-csharp",
        "css": "text/css",
        "csv": "text/csv",
        "dae": "model/vnd.collada+xml",
        "db": "application/vnd.sqlite3",
        "dcm": "application/dicom",
        "dicom": "application/dicom",
        "doc": "application/msword",
        "dockerfile": "text/x-dockerfile",
        "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "drc": "application/octet-stream",
        "dwg": "application/acad",
        "dxf": "application/dxf",
        "fbx": "application/octet-stream",
        "feather": "application/vnd.apache.arrow.file",
        "fit": "application/fits",
        "fits": "application/fits",
        "fts": "application/fits",
        "gcode": "text/plain",
        "glb": "model/gltf-binary",
        "gltf": "model/gltf+json",
        "go": "text/x-go",
        "graphql": "application/graphql",
        "gz": "application/gzip",
        "h5": "application/x-hdf",
        "hdf5": "application/vnd.hdf",
        "ifc": "application/x-step",
        "iges": "application/iges",
        "igs": "application/iges",
        "java": "text/x-java-source",
        "js": "text/javascript",
        "json": "application/json",
        "jsonl": "application/x-ndjson",
        "jsx": "text/javascript",
        "kicad_pcb": "application/octet-stream",
        "kicad_pro": "application/octet-stream",
        "kicad_sch": "application/octet-stream",
        "kicad_wks": "application/octet-stream",
        "kmz": "application/vnd.google-earth.kmz",
        "kt": "text/x-kotlin",
        "ktx2": "image/ktx2",
        "las": "application/octet-stream",
        "laz": "application/octet-stream",
        "less": "text/x-less",
        "log": "text/x-log",
        "lwo": "application/x-lwo",
        "makefile": "text/x-makefile",
        "mat": "application/x-matlab-data",
        "md": "text/markdown",
        "md2": "application/octet-stream",
        "mdd": "application/octet-stream",
        "mjs": "text/javascript",
        "mmd": "application/octet-stream",
        "mpd": "application/x-ldraw",
        "ndjson": "application/x-ndjson",
        "npy": "application/octet-stream",
        "npz": "application/zip",
        "nrrd": "application/octet-stream",
        "obj": "model/obj",
        "ods": "application/vnd.oasis.opendocument.spreadsheet",
        "parquet": "application/vnd.apache.parquet",
        "pcd": "application/octet-stream",
        "pdb": "chemical/x-pdb",
        "php": "text/x-php",
        "ply": "application/octet-stream",
        "pmx": "application/octet-stream",
        "ppt": "application/vnd.ms-powerpoint",
        "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "py": "text/x-python",
        "rar": "application/x-rar-compressed",
        "rb": "text/x-ruby",
        "rs": "text/x-rust",
        "sass": "text/x-sass",
        "scss": "text/x-scss",
        "sh": "text/x-sh",
        "sql": "text/x-sql",
        "sqlite": "application/vnd.sqlite3",
        "sqlite3": "application/vnd.sqlite3",
        "step": "application/step",
        "stl": "model/stl",
        "stp": "application/step",
        "tar": "application/x-tar",
        "tilt": "application/octet-stream",
        "toml": "text/x-toml",
        "ts": "text/typescript",
        "tsv": "text/tab-separated-values",
        "tsx": "text/typescript",
        "ttf": "font/ttf",
        "txt": "text/plain",
        "usdz": "model/vnd.usdz+zip",
        "vox": "application/octet-stream",
        "vrml": "model/vrml",
        "vtk": "application/octet-stream",
        "vtp": "application/xml",
        "wrl": "model/vrml",
        "xls": "application/vnd.ms-excel",
        "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xml": "text/xml",
        "xyz": "text/plain",
        "yaml": "text/yaml",
        "yml": "text/yaml",
        "zip": "application/zip",
        "zsh": "text/x-sh"
    ]

    /// Preview layout grouping for preferredContentSize
    enum PreviewLayoutGroup {
        case threeD
        case cad
        case pointCloud
        case texture
        case document

        var preferredSize: NSSize {
            switch self {
            case .threeD:
                return NSSize(width: 1280, height: 720)
            case .cad:
                return NSSize(width: 1280, height: 720)
            case .pointCloud:
                return NSSize(width: 1280, height: 720)
            case .texture:
                return NSSize(width: 1280, height: 1280)
            case .document:
                return NSSize(width: 1280, height: 720)
            }
        }

        static func forExtension(_ ext: String) -> PreviewLayoutGroup {
            switch ext {
        case "3dm": return .threeD
        case "3ds": return .threeD
        case "3mf": return .threeD
        case "7z": return .document
        case "amf": return .threeD
        case "arrow": return .document
        case "avro": return .document
        case "bash": return .document
        case "basis": return .texture
        case "brep": return .cad
        case "brp": return .cad
        case "bvh": return .threeD
        case "c": return .document
        case "cjs": return .document
        case "cpp": return .document
        case "cs": return .document
        case "css": return .document
        case "csv": return .document
        case "dae": return .threeD
        case "db": return .document
        case "dcm": return .document
        case "dicom": return .document
        case "doc": return .document
        case "dockerfile": return .document
        case "docx": return .document
        case "drc": return .threeD
        case "dwg": return .cad
        case "dxf": return .cad
        case "fbx": return .threeD
        case "feather": return .document
        case "fit": return .document
        case "fits": return .document
        case "fts": return .document
        case "gcode": return .threeD
        case "glb": return .threeD
        case "gltf": return .threeD
        case "go": return .document
        case "graphql": return .document
        case "gz": return .document
        case "h5": return .document
        case "hdf5": return .document
        case "ifc": return .cad
        case "iges": return .cad
        case "igs": return .cad
        case "java": return .document
        case "js": return .document
        case "json": return .document
        case "jsonl": return .document
        case "jsx": return .document
        case "kicad_pcb": return .document
        case "kicad_pro": return .document
        case "kicad_sch": return .document
        case "kicad_wks": return .document
        case "kmz": return .threeD
        case "kt": return .document
        case "ktx2": return .texture
        case "las": return .pointCloud
        case "laz": return .pointCloud
        case "less": return .document
        case "log": return .document
        case "lwo": return .threeD
        case "makefile": return .document
        case "mat": return .document
        case "md": return .document
        case "md2": return .threeD
        case "mdd": return .threeD
        case "mjs": return .document
        case "mmd": return .threeD
        case "mpd": return .threeD
        case "ndjson": return .document
        case "npy": return .document
        case "npz": return .document
        case "nrrd": return .threeD
        case "obj": return .threeD
        case "ods": return .document
        case "parquet": return .document
        case "pcd": return .pointCloud
        case "pdb": return .threeD
        case "php": return .document
        case "ply": return .pointCloud
        case "pmx": return .threeD
        case "ppt": return .document
        case "pptx": return .document
        case "py": return .document
        case "rar": return .document
        case "rb": return .document
        case "rs": return .document
        case "sass": return .document
        case "scss": return .document
        case "sh": return .document
        case "sql": return .document
        case "sqlite": return .document
        case "sqlite3": return .document
        case "step": return .cad
        case "stl": return .threeD
        case "stp": return .cad
        case "tar": return .document
        case "tilt": return .threeD
        case "toml": return .document
        case "ts": return .document
        case "tsv": return .document
        case "tsx": return .document
        case "ttf": return .document
        case "txt": return .document
        case "usdz": return .threeD
        case "vox": return .threeD
        case "vrml": return .threeD
        case "vtk": return .threeD
        case "vtp": return .threeD
        case "wrl": return .threeD
        case "xls": return .document
        case "xlsx": return .document
        case "xml": return .document
        case "xyz": return .pointCloud
        case "yaml": return .document
        case "yml": return .document
        case "zip": return .document
        case "zsh": return .document
            default:
                return .threeD
            }
        }
    }
}
